name = "Project Ozone 3 + Hysteria tweaks"
author = "thecazadorsniper"
version = "3.4.11F"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c31b02aae606219bca5aecb33899e84eae04967dbb0fc20056170ded3f1bace5"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
