name = "Project Ozone 3 + Hysteria tweaks"
author = "thecazadorsniper"
version = "3.4.11F"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "90c1b6cf0d09de5164cc776b616668fc9d15333fd89f67c632be2e17508486af"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
