name = "Project Ozone 3 + Hysteria tweaks"
author = "thecazadorsniper"
version = "3.4.11F"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "310b614128486ff333300153609983bc52b07e5830004282c6add84e8c4c171f"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
