name = "Project Ozone 3 + Hysteria tweaks"
author = "thecazadorsniper"
version = "3.4.11F"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b5dc74d8d9292917329dd398bf49886d1bdc41e93c0b72674a7aeda6ba4e15bc"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
