name = "Project Ozone 3 + Hysteria tweaks"
author = "thecazadorsniper"
version = "3.4.11F"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e902d743329d35ea3ed50afc57a84bd7d15cf85068501d1d3d2f976e0159da1c"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
