name = "Project Ozone 3 + Hysteria tweaks"
author = "thecazadorsniper"
version = "3.4.11F"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f5edffe085b0fe2591b47a128cd709724ad859fc65dd2569579190ddc91ce524"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
